#!/bin/bash

export LOGFILE=/dev/null
export BBE_REV=3.4.1
export BBE_HOME=~/asi/sw/asi2700/libs/dante-bbe

export here=`pwd`

export OCA_HOME=$here/../../../
export DANTE_PATH=${BBE_HOME}

echo "OCA_HOME: " $OCA_HOME
echo "DANTE_PATH: " $DANTE_PATH

make --makefile=makefileLIB $*
make --makefile=makefileBIN $*


